Blog/urls.py
from django.contrib import admin
from django.urls import path,include


#在总urls文件中使用命名空间。namespace可以更好的对各app的url进行区分
#之后只需要在各app的url中对应相应的namespace即可。


urlpatterns = [
    path('admin/', admin.site.urls),
    #path中第一个空缺可以填入总的url，对应app的url字符串拼在这后面。
    path('',include('blog_app.urls',namespace='blog_app')),
    path('',include('comments_app.urls',namespace='comments_app')),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path
from  blog_app import views

#视图函数命名空间。对应总urls中的视图空间。
#如有参数则需要在对应的视图函数中做处理，如下<int:pk>的pk会在views的detail中处理
#name作用类似于ID
app_name='blog_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('detail/<int:pk>/',views.ArticleDetailView.as_view(),name='detail'),
    path('index/',views.IndexView.as_view(),name='index'),
    path('archives/<int:year>/<int:month>/',views.ArchivesView.as_view(),name='archives'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='Category'),
    path('tag/<int:pk>/',views.TagView.as_view(),name = 'Tag'),
]

comments_app/urls.py
from django.urls import path
from . import views

app_name = "comments_app"
urlpatterns = [
path('comment/article/<int:article_pk>/',views.article_comment,name="article_comment"),
]

templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="detail.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="detail.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/category.html
{% extends 'base.html' %}

{% block main %}


{% endblock main %}

templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="detail.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="detail.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

                {% block main %}

                <article class="post post-{{ article.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ article.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ article.category }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ article.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ article.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ article.likes }}评论</a></span>
                            <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">

                        {{ article.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments_app:article_comment' article.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">

                            <div class="col-md-4">
                            <label for="{{ form.name.id_for_label }}">名字：</label>
                            {{ form.name }}
                            {{ form.name.errors }}
                            </div>

                            <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">邮箱：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>

                            <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">URL：</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>

                            <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">评论：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>    <!-- row -->

                    </form>

                    <div class="comment-list-panel">
                        <h3>评论列表</h3>
                        <ul class="comment-list list-unstyled">

  {% for comment in comment_list %}
  <li class="comment-item">
    <span class="nickname">{{ comment.name }}</span>
    <time class="submit-date">{{ comment.created_time }}</time>
    <div class="text">
      {{ comment.text }}
    </div>
  </li>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>
                    </div>
                </section>

                {% endblock main %}


                {% block toc %}

                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        {% for tag in article.tag.all %}
                        <li>
                            <a href={% url 'blog_app:Tag' tag.pk %}>{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                {% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
               {% for article in article_list %}

                <article class="post post-{{ article.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                      <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ article.category }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ article.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ article.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ article.likes }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ article.views }}</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ article.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ article.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty  %}
                   <div class="no-post">暂时还未发表文章</div>
               {% endfor %}
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->

{% if is_paginated %}
                <div class="pagination">
{#paginator ，即 Paginator 的实例。#}
{#page_obj ，当前请求页面分页对象。#}
{#is_paginated，是否已分页。只有当分页后页面超过两页时才算已分页。#}
{#object_list，请求页面的对象列表，和 article_list 等价。#}
                    <ul>
                      {% if page_obj.has_previous %}
                        <a href="?page={{page_obj.previous_page_number }}">上一页</a>
                      {% endif %}
                         <span class="current">第{{ page_obj.number }}页/共{{ paginator.num_pages }}页</span>
                        {% if page_obj.has_next %}
                         <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                        {% endif %}
                    </ul>
                </div>
{% endif %}
{% endblock main %}