Blog/urls.py
from django.contrib import admin
from django.urls import path,include


#在总urls文件中使用命名空间。namespace可以更好的对各app的url进行区分
#之后只需要在各app的url中对应相应的namespace即可。


urlpatterns = [
    path('admin/', admin.site.urls),
    #path中第一个空缺可以填入总的url，对应app的url字符串拼在这后面。
    path('',include('blog_app.urls',namespace='blog_app')),
    path('',include('comments_app.urls',namespace='comments_app')),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path
from  blog_app import views

#视图函数命名空间。对应总urls中的视图空间。
#如有参数则需要在对应的视图函数中做处理，如下<int:pk>的pk会在views的detail中处理
#name作用类似于ID
app_name='blog_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('detail/<int:pk>/',views.ArticleDetailView.as_view(),name='detail'),
    path('index/',views.IndexView.as_view(),name='index'),
    path('archives/<int:year>/<int:month>/',views.ArchivesView.as_view(),name='archives'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='Category'),
    path('tag/<int:pk>/',views.TagView.as_view(),name = 'Tag'),
]

templates/base.html
{% load staticfiles %}
<!-- 模板的基础页，在这个页面部署css等布局文件，留下对应block之后直接在对应模板里填充block即可 -->
{% load blog_app_tags %}
<!-- 引入自定义标签-->
<html>
<head>
    <title>Django Blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
      <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
      <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'blog/js/pace.min.js' %}"></script>
      <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog_app:index'%}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="detail.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
             {% block main %}

             {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}

                {% endblock toc %}
            {% block right %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_articles as recent_articles_list %}
                    <ul>

                        {% for article in recent_articles_list %}
                        <li>
                            <a href={{ article.get_absolute_url }}>{{ article.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                     {% archives as archive %}
                    {# archives返回一个date类型的迭代器用for in遍历#}
                     <ul>
                        {% for article_date in archive %}
                        <li>
                        {# {% url %} 可以解析视图函数 blog:archives 对应的 URL 模式 #}
                        {#herf写成：/archives/{{ date.year }}/{{ date.month }}/ 同样可以达到目的#}
                            <a href="{% url 'blog_app:archives' article_date.year article_date.month %}">{{ article_date.year }}年{{ article_date.month }}月</a>
                        </li>
                        {% empty  %}
                        暂无归档
                        {% endfor %}
                     </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as categotries %}
                    <ul>
                        {% for category in categotries %}
                        <li>
                            <a href="{% url 'blog_app:Category' category.pk %}">{{ category.name }} <span class="post-count">&nbsp   ({{ category.num_article }})</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% get_tags as tags %}
                        {% for Tag in tags %}
                        <li>
                            <a href="{%  url 'blog_app:Tag' Tag.pk %} ">{{ Tag.name }}</a>
                        </li>
                        {% empty %}暂无标签！

                        {% endfor %}

                    </ul>
                </div>
             {% endblock right %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">测试用</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="detail.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>